import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "export",
  // Photos are pre-generated by scripts/images.mjs and served through <Picture>;
  // static export has no image optimizer at runtime.
  images: { unoptimized: true },
  reactStrictMode: true,
  poweredByHeader: false,
  turbopack: { root: process.cwd() },
};

export default nextConfig;
