import localFont from "next/font/local";

/**
 * Mona Sans variable, self-hosted as ONE subset file (≈61 KB woff2):
 * wght 400–900, wdth 100–125, Basic Latin + Serbian Latin (č ć š ž đ) + the
 * punctuation the site uses. Generated by scripts/fonts.sh from the OFL source
 * in fonts/source (github.com/github/mona-sans). This replaces next/font/google
 * (two files, ≈130 KB) — see DECISIONS.md D-22 (LCP budget on mobile).
 */
export const mona = localFont({
  src: "../fonts/mona-sans-kraguj.woff2",
  variable: "--font-mona",
  weight: "400 900",
  style: "normal",
  display: "swap",
  adjustFontFallback: "Arial",
  declarations: [{ prop: "font-stretch", value: "100% 125%" }],
});

/** Doto dot-matrix, subset to digits . : – ~ (scoreboard numerals + easter egg only, ≥32px). */
export const doto = localFont({
  src: "../fonts/doto-scoreboard.woff2",
  variable: "--font-doto",
  weight: "400 900",
  display: "swap",
  preload: false,
  fallback: ["ui-monospace", "monospace"],
});
