// Generates styles/motion-tokens.css: the gymnastics eases that CSS cannot express
// as one cubic-bezier (elastic "wobble"/"swing"), sampled from the very same GSAP
// eases the motion code uses, so CSS and GSAP move identically. Run: node scripts/ease-tokens.mjs
import { writeFile } from "node:fs/promises";
import { gsap } from "gsap";

const SAMPLES = 48;
const linear = (name) => {
  const ease = gsap.parseEase(name);
  const pts = [];
  for (let i = 0; i <= SAMPLES; i++) pts.push(+ease(i / SAMPLES).toFixed(4));
  return `linear(${pts.join(", ")})`;
};

const css = `/* GENERATED by scripts/ease-tokens.mjs — do not edit by hand.
   Gymnastics motion vocabulary (see lib/motion-env.ts EASE):
   wobble = beam balance (elastic.out(1.1, 0.38)), swing = uneven-bars pendulum (elastic.out(1, 0.55)). */
:root {
  --ease-wobble: ${linear("elastic.out(1.1, 0.38)")};
  --ease-swing: ${linear("elastic.out(1, 0.55)")};
}
@supports not (animation-timing-function: linear(0, 1)) {
  :root {
    --ease-wobble: var(--ease-rebound);
    --ease-swing: var(--ease-rebound);
  }
}
`;
await writeFile("styles/motion-tokens.css", css);
console.log("styles/motion-tokens.css written");
