// Optimizes the official logo SVGs (svgo, floatPrecision 1) and generates the
// inline-sprite path data used by components/brand/Sprite.tsx.
// Reads only assets-source/logo/. Run: npm run svg
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { optimize } from "svgo";

const SRC = "assets-source/logo";
const svgoConfig = {
  floatPrecision: 1,
  multipass: true,
  plugins: [
    { name: "preset-default", params: { overrides: { cleanupIds: false } } },
  ],
};

function pathData(svg, file) {
  const d = svg.match(/<path[^>]*\sd="([^"]+)"/)?.[1];
  if (!d) throw new Error(`No <path d> in ${file}`);
  return d;
}

async function opt(file) {
  const raw = await readFile(`${SRC}/${file}`, "utf8");
  return optimize(raw, { ...svgoConfig, path: file }).data;
}

const leapSvg = await opt("kraguj-silueta.svg");
const wordmarkSvg = await opt("kraguj-wordmark.svg");
const leap = pathData(leapSvg, "kraguj-silueta.svg");
const wordmark = pathData(wordmarkSvg, "kraguj-wordmark.svg");

const out = `// GENERATED by scripts/svg.mjs — do not edit by hand.
// Source: assets-source/logo/kraguj-silueta.svg + kraguj-wordmark.svg (svgo, floatPrecision 1)

/** The leaping gymnast from the club logo, in logo coordinates (logo viewBox 0 0 490 213). */
export const LEAP_PATH = ${JSON.stringify(leap)};
/** Bounding viewBox of the silhouette inside the logo coordinate system. */
export const LEAP_VIEWBOX = { x: 262, y: 48, width: 230, height: 150 } as const;

/** Wordmark ("Gimnastički klub Kraguj") without the silhouette, viewBox 0 0 490 213. */
export const WORDMARK_PATH = ${JSON.stringify(wordmark)};
export const LOGO_VIEWBOX = { width: 490, height: 213 } as const;
`;
await writeFile("components/brand/sprite-paths.generated.ts", out);

// Optimized standalone logo files for OG image / icons / external use.
await mkdir("public/brand", { recursive: true });
for (const v of ["navy", "white"]) {
  await writeFile(`public/brand/kraguj-logo-${v}.svg`, await opt(`kraguj-logo-${v}.svg`));
}
await writeFile("public/brand/kraguj-silueta.svg", leapSvg);

const gz = (s) => import("node:zlib").then((z) => z.gzipSync(Buffer.from(s), { level: 9 }).length);
console.log(`leap: ${leap.length} B (${await gz(leap)} B gz) · wordmark: ${wordmark.length} B (${await gz(wordmark)} B gz)`);
