// Optimizes the official logo SVGs (svgo, floatPrecision 1) and generates the
// inline-sprite path data used by components/brand/Sprite.tsx.
// Also optimizes the pose family (assets-source/poses/*.svg) into
// components/brand/poses.generated.ts (docs/plan-figure-system.md §4, §7 Phase 1).
// Reads only assets-source/logo/ and assets-source/poses/. Run: npm run svg
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { optimize } from "svgo";
import { gzipSync } from "node:zlib";

const SRC = "assets-source/logo";
const svgoConfig = {
  floatPrecision: 1,
  multipass: true,
  plugins: [
    { name: "preset-default", params: { overrides: { cleanupIds: false } } },
  ],
};

function pathData(svg, file) {
  const d = svg.match(/<path[^>]*\sd="([^"]+)"/)?.[1];
  if (!d) throw new Error(`No <path d> in ${file}`);
  return d;
}

async function opt(file) {
  const raw = await readFile(`${SRC}/${file}`, "utf8");
  return optimize(raw, { ...svgoConfig, path: file }).data;
}

const leapSvg = await opt("kraguj-silueta.svg");
const wordmarkSvg = await opt("kraguj-wordmark.svg");
const leap = pathData(leapSvg, "kraguj-silueta.svg");
const wordmark = pathData(wordmarkSvg, "kraguj-wordmark.svg");

const out = `// GENERATED by scripts/svg.mjs — do not edit by hand.
// Source: assets-source/logo/kraguj-silueta.svg + kraguj-wordmark.svg (svgo, floatPrecision 1)

/** The leaping gymnast from the club logo, in logo coordinates (logo viewBox 0 0 490 213). */
export const LEAP_PATH = ${JSON.stringify(leap)};
/** Bounding viewBox of the silhouette inside the logo coordinate system. */
export const LEAP_VIEWBOX = { x: 262, y: 48, width: 230, height: 150 } as const;

/** Wordmark ("Gimnastički klub Kraguj") without the silhouette, viewBox 0 0 490 213. */
export const WORDMARK_PATH = ${JSON.stringify(wordmark)};
export const LOGO_VIEWBOX = { width: 490, height: 213 } as const;
`;
await writeFile("components/brand/sprite-paths.generated.ts", out);

// Optimized standalone logo files for OG image / icons / external use.
await mkdir("public/brand", { recursive: true });
for (const v of ["navy", "white"]) {
  await writeFile(`public/brand/kraguj-logo-${v}.svg`, await opt(`kraguj-logo-${v}.svg`));
}
await writeFile("public/brand/kraguj-silueta.svg", leapSvg);

const gz = (s) => import("node:zlib").then((z) => z.gzipSync(Buffer.from(s), { level: 9 }).length);
console.log(`leap: ${leap.length} B (${await gz(leap)} B gz) · wordmark: ${wordmark.length} B (${await gz(wordmark)} B gz)`);

// ---------------------------------------------------------------------------
// Pose family: assets-source/poses/<id>.svg → components/brand/poses.generated.ts
// Each source is one filled path (fill currentColor) in logo units at the logo figure's body
// scale (the #leap box is 230 × 150). Floor and contact anchors are root data attributes:
// data-floor="y" and data-<name>="x,y" (e.g. data-hand-l) → contacts.handL. Keys are sorted, so
// the output is deterministic. Poses are NOT part of the global sprite (Pose.tsx inlines them).
const POSE_SRC = "assets-source/poses";
const POSE_GZ_MAX = 600;
const poseFiles = (await readdir(POSE_SRC).catch(() => [])).filter((f) => f.endsWith(".svg")).sort();

const attrOf = (svg, name) => svg.match(new RegExp(`<svg[^>]*\\s${name}="([^"]*)"`))?.[1];
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const num = (s, file, what) => {
  const v = Number(s);
  if (!Number.isFinite(v)) throw new Error(`${file}: ${what} "${s}" is not a number`);
  return v;
};

const poses = [];
for (const file of poseFiles) {
  const id = file.replace(/\.svg$/, "");
  if (!/^[a-z][a-zA-Z0-9]*$/.test(id)) throw new Error(`${file}: pose ids are camelCase identifiers`);
  const raw = await readFile(`${POSE_SRC}/${file}`, "utf8");
  const svg = optimize(raw, { ...svgoConfig, path: file }).data;
  if ((svg.match(/<path\b/g) ?? []).length !== 1) throw new Error(`${file}: exactly one <path> expected`);
  if (!/<path[^>]*\sfill="currentColor"/.test(svg)) throw new Error(`${file}: the path must be fill="currentColor"`);
  const d = pathData(svg, file);
  const vb = (attrOf(svg, "viewBox") ?? "").trim().split(/[\s,]+/).map((v) => num(v, file, "viewBox"));
  if (vb.length !== 4) throw new Error(`${file}: viewBox needs 4 numbers`);
  const floorAttr = attrOf(svg, "data-floor");
  const contacts = [...svg.matchAll(/\sdata-([a-z][a-z0-9-]*)="([^"]*)"/g)]
    .filter(([, name]) => name !== "floor" && name !== "pose")
    .map(([, name, value]) => {
      const xy = value.split(",").map((v) => num(v, file, `data-${name}`));
      if (xy.length !== 2) throw new Error(`${file}: data-${name} must be "x,y"`);
      return [camel(name), xy];
    })
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const gz = gzipSync(Buffer.from(svg), { level: 9 }).length;
  if (gz > POSE_GZ_MAX) throw new Error(`${file}: ${gz} B gzipped (budget ${POSE_GZ_MAX} B)`);
  poses.push({ id, d, vb, floor: floorAttr === undefined ? undefined : num(floorAttr, file, "data-floor"), contacts, raw: svg.length, gz });
}
poses.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

/** barHandstand → POSE_BAR_HANDSTAND: one named export per pose, so a client chunk that needs one
 *  pose (camp routine, booking card) can import just that one and leave the rest tree-shaken. */
const poseConst = (id) => `POSE_${id.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase()}`;
const poseEntry = (p) => {
  const lines = [`export const ${poseConst(p.id)} = {`, `  d: ${JSON.stringify(p.d)},`];
  lines.push(`  viewBox: { x: ${p.vb[0]}, y: ${p.vb[1]}, width: ${p.vb[2]}, height: ${p.vb[3]} },`);
  if (p.floor !== undefined) lines.push(`  floor: ${p.floor},`);
  if (p.contacts.length) lines.push(`  contacts: { ${p.contacts.map(([k, [x, y]]) => `${k}: [${x}, ${y}]`).join(", ")} },`);
  lines.push("} as const satisfies PoseData;");
  return lines.join("\n");
};
const posesOut = `// GENERATED by scripts/svg.mjs — do not edit by hand.
// Source: assets-source/poses/*.svg (svgo, floatPrecision 1). Units: logo units at the logo
// figure's body scale (the #leap box is 230 × 150), so a pose drawn at the same scale as #leap has
// the same body size. floor = the y of the lowest ink for poses that stand on the floor or an
// apparatus; contacts = hand/foot anchors on the floor or apparatus (x, y in the viewBox).

export interface PoseData {
  readonly d: string;
  readonly viewBox: { readonly x: number; readonly y: number; readonly width: number; readonly height: number };
  readonly floor?: number;
  readonly contacts?: Readonly<Record<string, readonly [number, number]>>;
}

${poses.map(poseEntry).join("\n\n")}

/** Every pose by id (server components and <Pose>). Client chunks should import the one they need. */
export const POSES = {
${poses.map((p) => `  ${p.id}: ${poseConst(p.id)},`).join("\n")}
} as const satisfies Readonly<Record<string, PoseData>>;

export type PoseId = keyof typeof POSES;
`;
await writeFile("components/brand/poses.generated.ts", posesOut);
for (const p of poses) console.log(`pose ${p.id}: ${p.raw} B (${p.gz} B gz)`);
